# Generated by Django 4.2 on 2023-04-19 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectanalysisregistry',
            old_name='interpro_analyse',
            new_name='proteinortho_analyse',
        ),
        migrations.RenameField(
            model_name='projectanalysisregistry',
            old_name='pfam_analyse',
            new_name='rsat_analyse',
        ),
    ]
