# Generated by Django 4.2 on 2023-04-23 21:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0003_auto_20181106_1101'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0002_rename_interpro_analyse_projectanalysisregistry_proteinortho_analyse_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectanalysisregistryitem',
            name='rsat_analysed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectanalysisregistryitem',
            name='rsat_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistryitem',
            name='task_rsat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsat_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
        migrations.AlterField(
            model_name='projectanalysisregistry',
            name='proteinortho_analyse',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='projectanalysisregistryitem',
            name='registry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='item', to='api.projectanalysisregistry'),
        ),
        migrations.CreateModel(
            name='OrganismFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_id', models.CharField(blank=True, max_length=20, null=True)),
                ('feature', models.CharField(blank=True, max_length=10, null=True)),
                ('removed', models.BooleanField(default=False)),
                ('date_removed', models.DateTimeField(blank=True, null=True)),
                ('last_proteinortho_registry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_gene_feature_proteinortho', to='api.projectanalysisregistryitem')),
                ('last_rsat_registry', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_gene_feature_rsat', to='api.projectanalysisregistryitem')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='features', to='api.organism')),
                ('removed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='features_removed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='projectanalysisregistryitem',
            name='feature',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.PROTECT, related_name='analysis_registries_items', to='api.organismfeature'),
        ),
    ]
