# Generated by Django 4.2 on 2023-04-24 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_projectanalysisregistryitem_rsat_analysed_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='organism',
            options={},
        ),
    ]
