# Generated by Django 4.2 on 2023-04-24 02:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_organism_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='removed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterModelTable(
            name='organism',
            table=None,
        ),
    ]
