# Generated by Django 4.2 on 2023-07-10 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_organism_removed_alter_organism_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='BrazilianState',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='organism_accession',
            field=models.CharField(default='vazio', max_length=100),
        ),
    ]
