# Generated by Django 4.2 on 2023-09-01 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0003_auto_20181106_1101'),
        ('api', '0006_alter_promoter_options_profile_brazilianstate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='project',
            name='removed_by',
        ),
        migrations.RemoveField(
            model_name='projectanalysisregistryitem',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='projectanalysisregistryitem',
            name='registry',
        ),
        migrations.RemoveField(
            model_name='projectanalysisregistryitem',
            name='task_proteinortho',
        ),
        migrations.RemoveField(
            model_name='projectanalysisregistryitem',
            name='task_rsat',
        ),
        migrations.AlterModelOptions(
            name='promoter',
            options={},
        ),
        migrations.RemoveField(
            model_name='projectanalysisregistry',
            name='project',
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='proteinortho_analysed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='proteinortho_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='rsat_analysed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='rsat_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='task_proteinortho',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='proteinortho_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='task_rsat',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rsat_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
        migrations.DeleteModel(
            name='OrganismFeature',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectAnalysisRegistryItem',
        ),
    ]
