# Generated by Django 4.2 on 2023-09-24 04:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_promoter_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='promoter',
            options={'managed': False},
        ),
    ]
