# Generated by Django 4.2 on 2023-09-24 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_promoter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelregulatory',
            options={},
        ),
        migrations.AlterModelOptions(
            name='orthology',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promoter',
            options={},
        ),
        migrations.AlterModelOptions(
            name='protein',
            options={},
        ),
        migrations.AlterModelOptions(
            name='pwm',
            options={},
        ),
        migrations.AlterModelOptions(
            name='regulatoryinteraction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='tfbs',
            options={},
        ),
    ]
