# Generated by Django 4.2 on 2023-09-24 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_modelregulatory_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ModelRegulatory',
        ),
        migrations.DeleteModel(
            name='Orthology',
        ),
        migrations.DeleteModel(
            name='Promoter',
        ),
        migrations.DeleteModel(
            name='Protein',
        ),
        migrations.DeleteModel(
            name='Pwm',
        ),
        migrations.DeleteModel(
            name='RegulatoryInteraction',
        ),
        migrations.DeleteModel(
            name='Tfbs',
        ),
        migrations.DeleteModel(
            name='Gene',
        ),
    ]
