# Generated by Django 4.2 on 2023-09-24 16:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_delete_modelregulatory_delete_orthology_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gene',
            fields=[
                ('locus_tag', models.CharField(db_column='locus_tag', max_length=255, primary_key=True, serialize=False)),
                ('symbol_gene', models.CharField(blank=True, max_length=255, null=True)),
                ('is_tf', models.BooleanField(blank=True, null=True)),
                ('organism_accession', models.ForeignKey(blank=True, db_column='organism_accession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='org_accession', to='api.organism')),
            ],
            options={
                'db_table': 'gene',
            },
        ),
    ]
