# Generated by Django 4.2 on 2023-09-24 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_protein'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orthology',
            fields=[
                ('model_protein', models.ForeignKey(blank=True, db_column='model_protein', default='', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='ort_protein_model_protein', serialize=False, to='api.protein')),
                ('model_locus_tag', models.ManyToManyField(db_column='model_locus_tag', related_name='ort_model_locus_tag', to='api.protein')),
                ('model_organism_accession', models.ManyToManyField(db_column='model_organism_accession', related_name='ort_model_organism_accession', to='api.protein')),
                ('target_locus_tag', models.ManyToManyField(db_column='target_locus_tag', related_name='ort_target_locus_tag', to='api.protein')),
                ('target_organism_accession', models.ManyToManyField(db_column='target_organism_accession', related_name='ort_target_organism_accession', to='api.protein')),
                ('target_protein', models.ForeignKey(blank=True, db_column='target_protein', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_protein_target_protein', to='api.protein')),
            ],
            options={
                'db_table': 'orthology',
            },
        ),
    ]
