# Generated by Django 4.2 on 2023-09-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_orthology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promoter',
            fields=[
                ('locus_tag', models.OneToOneField(blank=True, db_column='locus_tag', default='', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='api.gene')),
                ('strand', models.CharField(blank=True, max_length=1, null=True)),
                ('source', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.IntegerField(blank=True, null=True)),
                ('stop', models.IntegerField(blank=True, null=True)),
                ('promoter_seq', models.CharField(blank=True, max_length=255, null=True)),
                ('organism_accession', models.ManyToManyField(db_column='organism_accession', related_name='prot_organism_accession', to='api.gene')),
            ],
            options={
                'db_table': 'promoter',
            },
        ),
    ]
