# Generated by Django 4.2 on 2023-09-24 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_promoter'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pwm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motif_id', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(blank=True, max_length=1, null=True)),
                ('tf_family', models.CharField(blank=True, max_length=255, null=True)),
                ('motif_type', models.CharField(blank=True, max_length=255, null=True)),
                ('msource_author', models.CharField(blank=True, max_length=255, null=True)),
                ('msource', models.CharField(blank=True, max_length=255, null=True)),
                ('pubmedid', models.CharField(blank=True, max_length=255, null=True)),
                ('locus_tag', models.ForeignKey(blank=True, db_column='locus_tag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.gene')),
                ('organism_accession', models.ManyToManyField(db_column='organism_accession', related_name='pwm_organism_accession', to='api.gene')),
            ],
            options={
                'db_table': 'pwm',
            },
        ),
    ]
