# Generated by Django 4.2 on 2023-09-24 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_pwm'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegulatoryInteraction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulatory_function', models.CharField(blank=True, max_length=255, null=True)),
                ('pubmedid_source', models.CharField(blank=True, max_length=255, null=True)),
                ('organism_accession', models.ManyToManyField(db_column='organism_accession', related_name='reg_organism_accession', to='api.gene')),
                ('tf_locus_tag', models.ForeignKey(blank=True, db_column='tf_locus_tag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_tf_locus_tag', to='api.gene')),
                ('tg_locus_tag', models.ForeignKey(blank=True, db_column='tg_locus_tag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='reg_tg_locus_tag', to='api.gene')),
            ],
            options={
                'db_table': 'regulatory_interaction',
            },
        ),
    ]
