# Generated by Django 4.2 on 2023-09-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_regulatoryinteraction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tfbs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strand', models.CharField(blank=True, max_length=255, null=True)),
                ('start', models.CharField(blank=True, max_length=255, null=True)),
                ('end', models.CharField(blank=True, max_length=255, null=True)),
                ('sequence', models.CharField(blank=True, max_length=255, null=True)),
                ('weight', models.CharField(blank=True, max_length=255, null=True)),
                ('pval', models.CharField(blank=True, max_length=255, null=True)),
                ('ln_pval', models.CharField(blank=True, max_length=255, null=True)),
                ('sig', models.CharField(blank=True, max_length=255, null=True)),
                ('organism_accession', models.ForeignKey(blank=True, db_column='organism_accession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tfbs_gene_organism_accession', to='api.gene')),
                ('pwm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.pwm')),
                ('regulatory_interaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.regulatoryinteraction')),
                ('tf_locus_tag', models.ForeignKey(blank=True, db_column='tf_locus_tag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tfbs_gene_tf_locus_tag', to='api.gene')),
                ('tg_locus_tag', models.ForeignKey(blank=True, db_column='tg_locus_tag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tfbs_gene_tg_locus_tag', to='api.gene')),
            ],
            options={
                'db_table': 'tfbs',
            },
        ),
    ]
