# Generated by Django 4.2 on 2023-09-24 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_tfbs'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelRegulatory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('regulatory_function', models.CharField(blank=True, max_length=255, null=True)),
                ('evidence', models.CharField(blank=True, max_length=255, null=True)),
                ('experiment', models.CharField(blank=True, max_length=255, null=True)),
                ('experimental_condition', models.CharField(blank=True, max_length=255, null=True)),
                ('pubmedid', models.CharField(blank=True, max_length=255, null=True)),
                ('publication', models.CharField(blank=True, max_length=255, null=True)),
                ('organism_accession', models.ForeignKey(blank=True, db_column='organism_accession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mr_gene_organism_accession', to='api.gene')),
                ('tf_locus_tag', models.ForeignKey(blank=True, db_column='tf_locus_tag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mr_gene_tf_locus_tag', to='api.gene')),
                ('tg_locus_tag', models.ForeignKey(blank=True, db_column='tg_locus_tag', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mr_gene_tg_locus_tag', to='api.gene')),
            ],
            options={
                'db_table': 'model_regulatory',
            },
        ),
    ]
