# Generated by Django 4.2 on 2023-09-24 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_modelregulatory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promoter',
            name='organism_accession',
        ),
        migrations.AddField(
            model_name='promoter',
            name='organism_accession',
            field=models.ForeignKey(db_column='organism_accession', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prot_organism_accession', to='api.gene'),
        ),
    ]
