# Generated by Django 4.2 on 2023-09-24 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_remove_promoter_organism_accession_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promoter',
            name='strand',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
