# Generated by Django 4.2 on 2023-09-25 02:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_alter_promoter_organism_accession_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='promoter',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='promoter',
            name='organism_accession',
            field=models.ForeignKey(blank=True, db_column='organism_accession', on_delete=django.db.models.deletion.DO_NOTHING, related_name='prot_organism_accession', to='api.organism'),
        ),
    ]
