# Generated by Django 4.2 on 2023-09-26 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0026_alter_promoter_unique_together_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teste',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_protein', models.CharField(db_column='target_locus_tag', max_length=255)),
                ('target_protein', models.CharField(db_column='target_protein', max_length=255)),
            ],
            options={
                'db_table': 'teste',
            },
        ),
        migrations.AddConstraint(
            model_name='teste',
            constraint=models.UniqueConstraint(fields=('model_protein', 'target_protein'), name='unique_orthology_teste'),
        ),
    ]
