# Generated by Django 4.2 on 2023-09-27 02:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0028_remove_orthology_model_locus_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orthology',
            name='model_locus_tag',
            field=models.ForeignKey(db_column='model_locus_tag', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ort_model_locus_tag', to='api.protein'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='model_organism_accession',
            field=models.ForeignKey(db_column='model_organism_accession', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ort_model_organism_accession', to='api.organism'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='model_protein',
            field=models.ForeignKey(blank=True, db_column='model_protein', on_delete=django.db.models.deletion.CASCADE, related_name='ort_protein_model_protein', to='api.protein'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='target_locus_tag',
            field=models.ForeignKey(db_column='target_locus_tag', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ort_target_locus_tag', to='api.protein'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='target_organism_accession',
            field=models.ForeignKey(db_column='target_organism_accession', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ort_target_organism_accession', to='api.organism'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='target_protein',
            field=models.ForeignKey(blank=True, db_column='target_protein', default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ort_protein_target_protein', to='api.protein'),
        ),
        migrations.AddConstraint(
            model_name='orthology',
            constraint=models.UniqueConstraint(fields=('model_organism_accession', 'model_locus_tag', 'model_protein', 'target_organism_accession', 'target_locus_tag', 'target_protein'), name='unique_orthology'),
        ),
    ]
