# Generated by Django 4.2 on 2023-09-28 01:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0029_orthology_id_alter_orthology_model_locus_tag_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='protein',
            name='uniparc',
        ),
        migrations.AddField(
            model_name='orthology',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='gene',
            constraint=models.UniqueConstraint(fields=('organism_accession', 'locus_tag'), name='unique_gene'),
        ),
    ]
