# Generated by Django 4.2 on 2023-09-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0030_remove_protein_uniparc_orthology_id_gene_unique_gene'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='modelregulatory',
            constraint=models.UniqueConstraint(fields=('organism_accession', 'tf_locus_tag', 'tg_locus_tag'), name='unique_model_regulatory'),
        ),
        migrations.AddConstraint(
            model_name='promoter',
            constraint=models.UniqueConstraint(fields=('organism_accession', 'locus_tag'), name='unique_promoter'),
        ),
        migrations.AddConstraint(
            model_name='protein',
            constraint=models.UniqueConstraint(fields=('organism_accession', 'locus_tag'), name='unique_protein'),
        ),
        migrations.AddConstraint(
            model_name='pwm',
            constraint=models.UniqueConstraint(fields=('organism_accession', 'locus_tag'), name='unique_pwm'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryinteraction',
            constraint=models.UniqueConstraint(fields=('organism_accession', 'tf_locus_tag', 'tg_locus_tag'), name='unique_regulatory_interaction'),
        ),
        migrations.AddConstraint(
            model_name='tfbs',
            constraint=models.UniqueConstraint(fields=('regulatory_interaction', 'organism_accession', 'tf_locus_tag', 'tg_locus_tag'), name='unique_tfbs'),
        ),
    ]
