# Generated by Django 4.2 on 2023-09-28 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0031_modelregulatory_unique_model_regulatory_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelregulatory',
            name='organism_accession',
            field=models.ForeignKey(blank=True, db_column='organism_accession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='mr_gene_organism_accession', to='api.organism'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='model_locus_tag',
            field=models.ForeignKey(db_column='model_locus_tag', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_model_locus_tag', to='api.protein'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='model_organism_accession',
            field=models.ForeignKey(db_column='model_organism_accession', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_model_organism_accession', to='api.organism'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='model_protein',
            field=models.ForeignKey(blank=True, db_column='model_protein', on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_protein_model_protein', to='api.protein'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='target_locus_tag',
            field=models.ForeignKey(db_column='target_locus_tag', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_target_locus_tag', to='api.protein'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='target_organism_accession',
            field=models.ForeignKey(db_column='target_organism_accession', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_target_organism_accession', to='api.organism'),
        ),
        migrations.AlterField(
            model_name='orthology',
            name='target_protein',
            field=models.ForeignKey(blank=True, db_column='target_protein', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_protein_target_protein', to='api.protein'),
        ),
        migrations.AlterField(
            model_name='protein',
            name='organism_accession',
            field=models.ForeignKey(blank=True, db_column='organism_accession', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='prot_gene_organism_accession', to='api.organism'),
        ),
    ]
