# Generated by Django 4.2 on 2023-10-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0033_alter_orthology_model_locus_tag_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='protein',
            name='unique_protein',
        ),
        migrations.AddConstraint(
            model_name='protein',
            constraint=models.UniqueConstraint(fields=('organism_accession', 'locus_tag', 'id'), name='unique_protein'),
        ),
    ]
