# Generated by Django 4.2 on 2023-10-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0035_remove_orthology_model_protein_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='regulatoryinteraction',
            name='unique_regulatory_interaction',
        ),
        migrations.AddConstraint(
            model_name='orthology',
            constraint=models.UniqueConstraint(fields=('id', 'model_organism_accession', 'model_locus_tag', 'target_organism_accession', 'target_locus_tag'), name='unique_orthology'),
        ),
        migrations.AddConstraint(
            model_name='regulatoryinteraction',
            constraint=models.UniqueConstraint(fields=('id', 'organism_accession', 'tf_locus_tag', 'tg_locus_tag'), name='unique_regulatory_interaction'),
        ),
    ]
