# Generated by Django 4.2 on 2023-10-02 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0036_remove_orthology_unique_orthology_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Orthology',
        ),
    ]
