# Generated by Django 4.2 on 2023-10-02 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0037_delete_orthology'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orthology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_locus_tag', models.ForeignKey(db_column='model_locus_tag', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_model_locus_tag', to='api.gene')),
                ('model_organism_accession', models.ForeignKey(db_column='model_organism_accession', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_model_organism_accession', to='api.organism')),
                ('model_protein', models.ForeignKey(db_column='model_protein', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='model_protein', to='api.protein')),
                ('target_locus_tag', models.ForeignKey(db_column='target_locus_tag', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_target_locus_tag', to='api.gene')),
                ('target_organism_accession', models.ForeignKey(db_column='target_organism_accession', default='', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='ort_target_organism_accession', to='api.organism')),
                ('target_protein', models.ForeignKey(db_column='target_protein', default='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='target_protein', to='api.protein')),
            ],
            options={
                'db_table': 'orthology',
            },
        ),
        migrations.AddConstraint(
            model_name='orthology',
            constraint=models.UniqueConstraint(fields=('id', 'model_organism_accession', 'model_locus_tag', 'target_organism_accession', 'target_locus_tag', 'model_protein', 'target_protein'), name='unique_orthology'),
        ),
    ]
