# Generated by Django 4.2 on 2023-10-13 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('django_celery_results', '0003_auto_20181106_1101'),
        ('api', '0038_orthology_orthology_unique_orthology'),
    ]

    operations = [
        migrations.CreateModel(
            name='CalculateCentralityRegistry',
            fields=[
                ('locus_tag', models.ForeignKey(db_column='locus_tag', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='calculate_centrality_gene_locus_tag', serialize=False, to='api.gene')),
                ('degree', models.FloatField()),
                ('closeness', models.FloatField()),
                ('betweenness', models.FloatField()),
                ('eigenvector', models.FloatField()),
                ('harmonic', models.FloatField()),
            ],
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='betweenness_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='closeness_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='create_graph_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='degree_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='eigenvector_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='harmonic_error',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='task_calculate_betweenness',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculate_betweenness_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='task_calculate_closeness',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculate_closeness_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='task_calculate_degree',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculate_degree_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='task_calculate_eigenvector',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculate_eigenvector_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='task_calculate_harmonic',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='calculate_harmonic_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
        migrations.AddField(
            model_name='projectanalysisregistry',
            name='task_create_graph',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_graph_analysis_registry_item', to='django_celery_results.taskresult'),
        ),
    ]
