# Generated by Django 4.2 on 2023-10-13 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0039_calculatecentralityregistry_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calculatecentralityregistry',
            name='betweenness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatecentralityregistry',
            name='closeness',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatecentralityregistry',
            name='degree',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatecentralityregistry',
            name='eigenvector',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calculatecentralityregistry',
            name='harmonic',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
