# Generated by Django 4.2 on 2023-10-17 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0040_alter_calculatecentralityregistry_betweenness_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teste',
        ),
    ]
